version: '2.3'
services:
  catalog:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bacula
      MYSQL_USER: bacula
      MYSQL_PASSWORD: bacula
    volumes:
      - ./catalog/data:/var/lib/mysql
      - ./catalog/db_scripts:/docker-entrypoint-initdb.d/
    networks: 
      default:
    restart: always
  director:
    image: 172.16.0.145:5000/bacula_director:latest
    tty: true
    volumes:
      - type: bind
        source: ./director/data
        target: /etc/bacula
    networks:
      rede_gerencia:
        ipv4_address: 172.16.0.180
      default:    
    depends_on: 
      - catalog
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost/webacula/"]
      interval: 5 minutes
      timeout: 5s
      retries: 3
      start_period: 50s
networks:
  rede_gerencia:
    external: true
  default: