version: '2'
services:
  catalog:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bacula
      MYSQL_USER: bacula
      MYSQL_PASSWORD: bacula
    volumes:
       - ./catalog/data:/var/lib/mysql
       - ./catalog/db_scripts:/docker-entrypoint-initdb.d/
  director:
    image: 172.16.0.145:5000/bacula_director:latest
    tty: true
    # ports: 
    #   - "9001:80"
    volumes:
      - ./director/data:/etc/bacula/
    networks:
      rede_gerencia:
        ipv4_address: 172.16.0.180
    depends_on: 
      - catalog
networks:
  rede_gerencia: