version: '2.3'
services:  
  catalog:
    container_name: bacula_catalog
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bacula
      MYSQL_USER: bacula
      MYSQL_PASSWORD: bacula
    volumes:
      - ./catalog/data:/var/lib/mysql
      - ./catalog/db_scripts:/docker-entrypoint-initdb.d/
    networks: 
      default:
    restart: always
  director:
    container_name: bacula_director
    image: 172.16.0.145:5000/bacula_director:latest
    tty: true
    volumes:
      - type: bind
        source: ./director/data
        target: /etc/bacula
    networks:
      rede_gerencia:
        ipv4_address: 172.16.0.181
      default:    
    depends_on: 
      - catalog
    restart: always
  webacula:
    container_name: webacula
    image: 172.16.0.145:5000/webacula:latest
    tty: true    
    networks:
      rede_gerencia:
        ipv4_address: 172.16.0.180
      default:    
    depends_on: 
      - director
      - catalog
    restart: always
  bdashboard:
    container_name: bdashboard
    image: 172.16.0.145:5000/bdashboard:latest
    tty: true    
    networks:
      rede_gerencia:
        ipv4_address: 172.16.0.183
      default:    
    depends_on: 
      - director
      - catalog
    restart: always
networks:
  rede_gerencia:
    external: true
  default: